#!/bin/sh

PATH=/usr/bin:/bin:/usr/sbin:/sbin export PATH

profileName="GoogleChrome.mobileconfig"

setupPath="/private/var/db/ConfigurationProfiles/Setup/"

resources=$(dirname "$0")
profilePath="${resources}/${profileName}"

if [ "$3" = "/" ] ; then
    profiles -I -F "${profilePath}"
else
    mkdir -p "$3${setupPath}"
    cp "$3${profilePath}" "$3${setupPath}${profileName}"
    /bin/rm -f "$3${profilePath}.profileSetupDone"
fi
