#!/bin/sh

# SourceCodePro preinstall script

PATH=/usr/bin:/bin:/usr/sbin:/sbin export PATH

# find and delete any SourceCodePro file in any user folder

find "$3"/Users/*/Library/Fonts -iname "SourceCodePro*.?tf" -delete

