#!/bin/bash

# SourceCodePro preinstall script

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

# find and delete any SourceCodePro file in any user folder

find "$3"/Users/*/Library/Fonts -iname "SourceCodePro*.?tf" -delete
